[package]
name = "isla-cac"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
isla-lib = { version = "0.1.0", path = "../isla-lib" }
